services:
  # Node.JS Connection Manager Service
  javaservice:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - default

  # Pilates Database Service
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pilates_db
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default

# Development Network
networks:
  default:
    driver: bridge
