services:
  # Node.JS Connection Manager Service
  web:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/usr/app/
      - /usr/app/nodejs/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - default

  # Pilates Database Service
  postgres:
    image: postgres:latest
    container_name: db_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pilates_db
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default

# Development Network
networks:
  default:
    driver: bridge
